:sparkles: (taeyoung/feature/components/#3) 인풋 박스 컴포넌트 추가
ILGOB/Plinic-Front pull request #11
Opened 2022-08-11 17:53 UTC by overtae

<table>
  <tr>
    <td>props 이름</td>
    <td>자료형</td>
    <td>종류</td>
  </tr>
  <tr>
    <td rowspan="4"><code>usedFor</code></td>
    <td rowspan="4"><code>String</code></td>
    <td><code>nickname</code> : 닉네임 입력</td>
  </tr>
  <tr>
    <td><code>search</code> : 검색어 입력</td>
  </tr>
  <tr>
    <td><code>title</code> : 게시글 제목 입력</td>
  </tr>
  <tr>
    <td><code>content</code> : 게시글 내용 입력</td>
  </tr>
</table>

위 4가지 인풋 박스 디자인과 기능 구현 완료했습니다.
닉네임, 검색 인풋 박스는 엔터키 입력 시 값이 제출되도록 했습니다.

2022-08-12 17:40 UTC, overtae commented
커밋 메시지를 잘못 작성해서 reset을 했는데.. pr을 보내면 기록이 남는군요.. 죄송합니다...

2022-08-13 14:59 UTC, HalamLee requested changes
리뷰 확인 후 수정해서 다시 pr 보내주세요!

2022-08-13 14:59 UTC, HalamLee commented on plinic/src/components/input/Input.jsx
> +import styled, { css } from 'styled-components';
![image](https://user-images.githubusercontent.com/87893624/184498621-4fd3a521-bd77-42a8-b277-eded579c45f2.png)
[참고 블로그](https://yumyumlog.tistory.com/244)

styled-components에서 css 헬퍼는 props의 조건에 따라 스타일을 다양하게 주는 경우에 보기 쉽게 하기 위해 사용한다고 합니다. 이 파일에서 css 헬퍼를 적용한 부분을 보면 조건에 따라 다양한 스타일을 주는 경우가 아니었기에 css 헬퍼를 사용하지 않고 styled만 사용하는 것은 어떨지 제안드립니다!
```suggestion
import styled from 'styled-components';
```

2022-08-13 14:59 UTC, HalamLee commented on plinic/src/components/input/Input.jsx
> +  };
![image](https://user-images.githubusercontent.com/87893624/184498812-ab1491ce-6519-4f2d-8b1c-51a44e5e4d66.png)
[참고 블로그](https://choisuhyeok.tistory.com/58)

현재 조건에 따라 return 하는 것이 다르고, 이것을 switch문을 사용해서 구현했는데 객체를 사용해 lookup table 을 만들면 더 깔끔하게 만들 수 있습니다.

```suggestion
const placeholder = {
  nickname: '닉네임',
  search: '검색어',
  title: '제목',
};

const getPlaceholder = (usedFor) => placeholder2[usedFor] || '내용';

// 함수를 사용하거나 객체를 바로 사용하거나
console.log(placeholder['nickname']); // 닉네임
console.log(getPlaceholder('nickname')); // 닉네임

console.log(getPlaceholder('search')); // 검색어
console.log(getPlaceholder('title')); // 제목
console.log(getPlaceholder()); // 내용
```

위와 같이 만들 수 있겠으나 이 코드는 참고용으로 이해하시고, 태영님한테 맞게끔 추가적으로 손 보면 좋을 것 같습니다. 아래에서 사용한 다른 switch문도 이렇게 객체를 이용한 형태로 수정하면 좋을 것 같아요😊

2022-08-13 14:59 UTC, HalamLee commented on plinic/src/components/input/Input.jsx
> +  const placeholder = () => {
혹시 여기 파라미터로 usedFor를 넣어야 하는 건 아닐까요? 현재 상태에서 코드가 잘 동작하나요?
```suggestion
const placeholder = (usedFor) => {
```

2022-08-13 14:59 UTC, HalamLee commented on plinic/src/components/input/Input.jsx
> +        {usedFor === 'nickname' ? <span></span> : usedFor === 'search' && <div>🔍</div>}
여기서 usedFor가 nickname일 때 비어 있는 span 태그를 넣는 이유가 궁금합니다!

2022-08-13 14:59 UTC, HalamLee commented on plinic/src/components/input/Input.jsx
> +const NAVY = ({ theme }) => theme.color.navy;
이렇게 상수를 만들어서 사용하는 것 너무 좋은 것 같아요!
가독성이 정말 좋습니다!👍🏻👍🏻

2022-08-13 14:59 UTC, HalamLee commented on plinic/src/components/input/Input.jsx
> +const NickName = css`
조건에 따라 다른 스타일을 주는 게 아니므로 css 헬퍼가 아니라 styled를 사용하면 좋을 것 같아요! 다른 곳에서 사용한 css 헬퍼도 마찬가지입니다!

2022-08-13 14:59 UTC, HalamLee commented on plinic/src/components/input/Input.jsx
> +  }}
여기도 객체를 이용해 lookup table을 만들어 보면 좋을 것 같습니다!

2022-08-13 15:11 UTC, HalamLee reviewed
리뷰 확인 후 답변 부탁드립니다!

2022-08-13 15:11 UTC, HalamLee commented on plinic/src/components/pagination/Pagination.jsx
> +};
객체로 만들어서 사용한 방식 너무 좋습니다! 다만 각 키들을 상수로 사용하는 건 어떨까요?
아래는 예시입니다.
앗 그리고 객체를 변수에 넣어서 사용하는 것이므로 컴포넌트가 아니기 때문에 첫글자를 대문자로 쓰지 않아도 됩니다. 아니면, 혹시 theme를 사용하면 value에서 theme를 사용하기 때문에 에러가 나던가요?
```suggestion
const theme = {
  NAVY: ({ theme }) => theme.color.navy,
  WHITE: ({ theme }) => theme.color.white,
  GRAY: ({ theme }) => theme.color.gray,
  FONT: [({ theme }) => theme.font.size['14'], ({ theme }) => theme.font.weight['normal']],
  BOLD: ({ theme }) => theme.font.weight['bold'],
  CENTER: ({ theme }) => theme.align.flexCenter,
  CENTER_COLUMN: ({ theme }) => theme.align.flexCenterColumn,
};

2022-08-17 18:21 UTC, overtae commented on plinic/src/components/input/Input.jsx
> +        {usedFor === 'nickname' ? <span></span> : usedFor === 'search' && <div>🔍</div>}
인풋 박스 애니메이션을 주려고 넣었습니다.
input 태그는 before 나 after가 안된다고 해서 원하는 애니메이션을 어떻게 줘야 할지 몰라서 이런 식으로 했습니다 ㅠㅠ..

2022-08-17 18:22 UTC, overtae commented on plinic/src/components/input/Input.jsx
> +  const placeholder = () => {
동작은 하지만 넣는 게 좋아 보여서 수정하겠습니다.

2022-08-18 14:22 UTC, HalamLee approved these changes
theme 으로 적용할 수 있는 부분이 보여서 리뷰 추가했습니다! 다음에 추가 작업할 때 반영해주면 좋을 것 같아요😀

2022-08-18 14:22 UTC, HalamLee commented on plinic/src/pages/test/TY.jsx
> +  align-items: center;
```suggestion
  ${({ theme }) => theme.align.flexCenterColumn};
```

2022-08-18 14:22 UTC, HalamLee commented on plinic/src/pages/test/TY.jsx
> +  flex-direction: column;
```suggestion
  ${({ theme }) => theme.align.flexCenterColumn};
```

2022-08-18 14:22 UTC, merged